[phases.setup]
aptPkgs = ["tesseract-ocr", "libtesseract-dev"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "python -m gunicorn app:app --workers=1 --threads=2 --timeout=120 --bind 0.0.0.0:$PORT"
