[phases.setup]
aptPkgs = ["tesseract-ocr"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[start]
cmd = "gunicorn app:app --bind 0.0.0.0:$PORT --timeout 120 --workers 2"
